--CREATE TABLE IF NOT EXISTS photoz (
--    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
--    file_name VARCHAR(255),
--    content_type VARCHAR(255),
--    data BINARY
--);

--create table if not exists photoz (
--    id bigint identity primary key,
--    file_name varchar(255),
--    content_type varchar(255),
--    data binary
--);

--CREATE TABLE IF NOT EXISTS photoz (
--    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    file_name VARCHAR(255),
--    content_type VARCHAR(255),
--    data BINARY
--);


create table if not exists photoz (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    file_name varchar(255),
    content_type varchar(255),
    data binary large object
);